### ISSUE TITLE
Incorrect behaviour, verbose JSON is produced default(liberator-transit 0.3.0)

### ISSUE THREAD

**Issue by kfh** [sattvik/liberator-transit#6]
...which means i have to put  :as-response (as-response {:allow-json-verbose? false})
in all my resource configurations or else it will blow up with a stacktrace.

**Comment by atroche** [comment]
just ran into this problem too. NullPointerExceptions aren't fun!

**Comment by sattvik** [comment]
This should be now fixed in 0.3.1.  I apologise for the unacceptable delay in getting this fix in.
